_MAINNET_CKBTC_LEDGER_CANISTER = 'mxzaz-hqaaa-aaaar-qaada-cai'
_MAINNET_CKETH_LEDGER_CANISTER = 'ss2fx-dyaaa-aaaar-qacoq-cai'

CKBTC_CANISTER = _MAINNET_CKBTC_LEDGER_CANISTER

TIME_PERIOD_SECONDS = 0
TRANSACTION_BATCH_SIZE = 5