name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_run:
    workflows: ["Test", "Test IC"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:  # Allows manual triggering without restrictions

jobs:
  deploy:
    # Only run if the workflow_run event was successful or if it's a release or manual dispatch
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: python -m build
      
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine check dist/*
        twine upload dist/*
